version: '3'

services:
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}

  frontend:
    build:
      context: ./frontend/projects-front
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - web

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - web
      - frontend

volumes:
  db_data: